// src/components/solid/Greeting.tsx
import { createSignal, onMount } from 'solid-js'
import { container } from '@/lib/container'
import type { IMessageService } from '@/lib/container'
import styles from './Greeting.module.css'

export function Greeting() {
  const [message, setMessage] = createSignal('')

  onMount(() => {
    const messageService = container.get<IMessageService>('IMessageService')
    setMessage(messageService.getMessage())
  })

  return (
    <div class={styles.solidComponent}>
      <p>{message()}</p>
    </div>
  )
}

// src/components/svelte/Greeting.svelte
<script lang="ts">
  import { container } from '@/lib/container'
  import type { IMessageService } from '@/lib/container'

  let message = ''

  $: {
    const messageService = container.get<IMessageService>('IMessageService')
    message = messageService.getMessage()
  }
</script>

<div class="svelte-component">
  <p>{message}</p>
</div>

<style>
  .svelte-component {
    font-family: system-ui, sans-serif;
  }
</style>
